#!/usr/bin/env bash

# Top level manager for @CNG's system configuration scripts

# Script location determination accounting for symlinked script name
# http://stackoverflow.com/a/246128/172602
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
APP_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
source "$APP_ROOT/lib/common.bash"

hdlr_install () {
  # defaults to base
  if (( $# > 0 )); then
    for module in "$@"; do
      module_install "$module"
    done
    return 0
  fi
  module_install base
}

hdlr_reinstall () {
  # defaults to --all
  if (( $# > 0 )); then
    for module in "$@"; do
      module_reinstall "$module"
    done
    return 0
  fi
  module_reinstall --all
}

hdlr_upgrade () {
  # defaults to --all
  if (( $# > 0 )); then
    for module in "$@"; do
      module_upgrade "$module"
    done
    return 0
  fi
  module_upgrade --all
}

hdlr_remove () {
  # does not default to --all
  (( $# == 0 )) && print_usage
  for module in "$@"; do
    module_remove "$module"
  done
}

hdlr_cleanup () {
  (( $# == 0 )) || print_usage
  packages_cleanup
}

hdlr_list () {
  module_list "$@"
}

hdlr_tests () {
  (( $# == 0 )) || print_usage
  source "$APP_ROOT/lib/tests.bash"
  main_tests
}

main () {
  cd "$( dirname "${BASH_SOURCE[0]}" )"
  case ${1:-} in
    install   ) hdlr_install   "${@:2}" ;;
    reinstall ) hdlr_reinstall "${@:2}" ;;
    upgrade   ) hdlr_upgrade   "${@:2}" ;;
    remove    ) hdlr_remove    "${@:2}" ;;
    cleanup   ) hdlr_cleanup   "${@:2}" ;;
    list      ) hdlr_list      "${@:2}" ;;
    tests     ) hdlr_tests     "${@:2}" ;;
    * | help  ) print_usage             ;;
  esac
}

main $@

#TODO autocomplete http://askubuntu.com/questions/68175/how-to-create-script-with-auto-complete
