#!/usr/bin/env bash

# Manager for @CNG's system configuration

APP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
source 'lib/common.bash'

hdlr_install () {
  (( $# == 0 )) && print_usage
  for module in "$@"; do
    module_install "$module"
  done
}

hdlr_upgrade () {
  if (( $# > 0 )); then
    for module in "$@"; do
      module_upgrade "$module"
    done
    return 0
  fi
  module_upgrade --all
}

hdlr_remove () {
  (( $# == 0 )) && print_usage
  for module in "$@"; do
    module_remove "$module"
  done
}

hdlr_cleanup () {
  (( $# == 0 )) || print_usage
  packages_cleanup
}

hdlr_tests () {
  (( $# == 0 )) || print_usage
  source 'lib/tests.bash'
  main_tests
}

main () {
  cd "$( dirname "${BASH_SOURCE[0]}" )"
  case $1 in
    install ) hdlr_install "${@:2}" ;;
    upgrade ) hdlr_upgrade "${@:2}" ;;
    remove  ) hdlr_remove  "${@:2}" ;;
    cleanup ) hdlr_cleanup "${@:2}" ;;
    tests   ) hdlr_tests   "${@:2}" ;;
    *       ) print_usage           ;;
  esac
}

main $@

#TODO autocomplete http://askubuntu.com/questions/68175/how-to-create-script-with-auto-complete
